name = "Greek dev"
license = "MIT"
licenselink = "https://github.com/pappanick/hugo-theme-thegreekdev/blob/master/LICENSE.md"
description = "My blog based on yingyang."
homepage = "https://thegreek.dev"
tags = [
  "blog",
  "minimal",
  "minimalist",
  "responsive",
  "simple",
  "clean",
  "personal",
  "art"
]
features = ["blog"]
min_version = "0.50"

[params]
staticPrefix = ""
extraCSSFiles = ["css/foo.css", "css/bar.css"]
# extraCSSFiles = []

[author]
  name = "Nick Pappas"
  homepage = "https://thegreek.dev"
