baseURL = "https://www.thegreek.dev"
languageCode = "en-us"
title = "A Greek Dev Blog"
theme = "yinyang"
DefaultContentLanguage = "en"

[author]
  name = "Nick Pappas"
  homepage = "https://www.thegreek.dev/"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1
  [languages.cn]
    contentDir = "content/el"
    languageName = "Greek"
    weight = 1

[params]
disqus = "dbb66ktmbj@privaterelay.appleid.com" # disqus account name
extraHead = ''
mainSections = ["posts"]

[[params.socials]]
name = "RSS"
link = "/index.xml"

[[params.socials]]
name = "About"
link = "https://joway.io"
